manajemen_cuti/urls.py
from django.urls import path
from . import views

app_name = 'manajemen_cuti'

urlpatterns = [
    path('cuti', views.listCuti, name='list_cuti'),
    path('cuti/create', views.addCuti, name='add_cuti'),
    path('cuti/approve_cuti/<int:pk>', views.approveCuti, name='approve_cuti'),
    path('cuti/cancel_cuti/<int:pk>', views.cancelCuti, name='cancel_cuti'),
    path('cuti/reject_cuti/<int:pk>', views.rejectCuti, name='reject_cuti'),

    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

manajemen_cuti/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

# Create your models here
class Cuti(models.Model):
    """Model definition for Cuti."""
    CUTI_CHOICES = [
        ('tahunan', 'Tahunan'),
        ('sakit', 'Sakit'),
        ('darurat', 'Darurat')
    ]

    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('disetujui', 'Disetujui'),
        ('ditolak', 'Ditolak'),
        ('dibatalkan', 'Dibatalkan'),
    ]

    # TODO: Define fields here
    karyawan        = models.ForeignKey(User, on_delete = models.CASCADE)
    jenis_cuti      = models.CharField(
                        max_length = 16,
                        choices = CUTI_CHOICES,
                        default = 'tahunan'
                        )                        
    tgl_permohonan  = models.DateTimeField(default = timezone.now)
    tgl_mulai       = models.DateTimeField()
    tgl_selesai     = models.DateTimeField()
    status          = models.CharField(
                        max_length = 16,
                        choices = STATUS_CHOICES,
                        default = 'pending'
                        )
    alasan          = models.CharField(max_length = 32, blank=True, null=True)
    sisa_cuti       = models.IntegerField()

    class Meta:
        """Meta definition for Cuti."""

        verbose_name = 'Cuti'
        verbose_name_plural = 'Cutis'

    def __str__(self):
        """Unicode representation of Cuti."""
        return f"{self.karyawan}-{self.jenis_cuti}-{self.status}"

    def lama_cuti(self):
        return (self.tgl_selesai - self. tgl_mulai).days + 1
    
    def clean(self):
        if self.jenis_cuti == 'tahunan' and self.sisa_cuti is not None and self.sisa_cuti < 1:
            raise ValidationError("Sisa cuti tidak mencukupi")
            
    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)
            

manajemen_cuti/forms.py
from django import forms
from .models import *
from django.forms import DateTimeInput

class CutiForm(forms.ModelForm):
    """Form definition for Cuti."""

    class Meta:
        """Meta definition for Cutiform."""

        model = Cuti
        fields = ['jenis_cuti', 'tgl_mulai', 'tgl_selesai', 'alasan', 'sisa_cuti']
        widgets = {
            'tgl_mulai' : DateTimeInput(
                attrs={'type':'datetime-local', 'class':'form-control'}
            ),
            'tgl_selesai' : DateTimeInput(
                attrs={'type':'datetime-local', 'class':'form-control'}
                ),
        }
            
    def __init__(self, *args, **kwargs):
        super(CutiForm, self).__init__(*args, **kwargs)
        self.fields['jenis_cuti'].widget.attrs.update({'id':'jenis_cuti', 'class':'form-control'})
        # self.fields['status'].widget.attrs.update({'id':'status', 'class':'form-control'})
        self.fields['alasan'].widget.attrs.update({'id':'alasan', 'class':'form-control'})
        self.fields['tgl_mulai'].input_formats = ['%Y-%m-%dT%H:%M']
        self.fields['tgl_selesai'].input_formats = ['%Y-%m-%dT%H:%M']

    def clean(self):
        cleaned_data = super().clean()
        tgl_mulai = cleaned_data.get('tgl_mulai')
        tgl_selesai = cleaned_data.get('tgl_selesai')
        sisa_cuti = cleaned_data.get('sisa_cuti')

        if tgl_mulai and tgl_selesai:
            if tgl_selesai < tgl_mulai:
                raise forms.ValidationError("Tanggal selesai tidak boleh sebelum tanggal mulai")
        
            if tgl_mulai < timezone.now():
                raise forms.ValidationError("Tanggal mulai tidak boleh di masa lalu")
        # return cleaned_data
        try:
            sisa_cuti = int(sisa_cuti)
            if sisa_cuti < 1:
                raise forms.ValidationError("Sisa cuti tidak mencukupi")
        except (ValueError, TypeError):
            raise forms.ValidationError("sisa cuti tidak valid")

        return cleaned_data

manajemen_cuti/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import user_passes_test, login_required
from .models import *
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout, authenticate
from openpyxl import Workbook
from django.http import HttpResponse


# Create your views here.
@login_required
def listCuti(request):
    # pending_count = Cuti.objects.filter(status='pending').count()
    if request.user.is_staff:
        cuti = Cuti.objects.all().order_by('-tgl_permohonan')
    else:
        cuti = Cuti.objects.filter(karyawan=request.user).order_by('-tgl_permohonan')
    
    context = {
        'title' : "Daftar Permohonan Cuti",
        'cutis' : cuti,
    }
    return render(request, 'manajemen_cuti/list.html', context)

@login_required
def addCuti(request):
    form = CutiForm(request.POST or None)
    if request.method =='POST':
        print("==== DEBUG POST ====")
        for key in request.POST:
            print(f"{key} → {request.POST.getlist(key)}")  # penting: pakai getlist

        if form.is_valid():
            cuti = form.save(commit=False)
            cuti.karyawan = request.user
            cuti.status = 'pending'
            cuti.sisa_cuti = 6
            cuti.save()
            print(request.POST)
            print("Tipe alasan:", type(request.POST.get('alasan')))

            return redirect('manajemen_cuti:list_cuti')
        else:
            print("forms error", form.errors)

    context = {
        'title' : 'Permohonan Cuti',
        'forms' : form,
    }

    return render(request, 'manajemen_cuti/create.html', context)

@user_passes_test(lambda u:u.is_staff)
def approveCuti(request, pk):
    cuti = Cuti.objects.get(pk=pk)
    cuti.status = 'disetujui'
    cuti.save()

    return redirect('manajemen_cuti:list_cuti')

@user_passes_test(lambda u:u.is_staff)
def cancelCuti(request, pk):
    cuti = Cuti.objects.get(pk=pk)
    cuti.status = 'dibatalkan'
    cuti.save()

    return redirect('manajemen_cuti:list_cuti')

@user_passes_test(lambda u:u.is_staff)
def rejectCuti(request, pk):
    cuti = Cuti.objects.get(pk=pk)
    cuti.status = 'ditolak'
    cuti.save()

    return redirect('manajemen_cuti:list_cuti')

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('manajemen_cuti:list_cuti')
            else:
                # messages.error(request, 'Username atau password salah.')
                context = {
                    'forms': form,
                    'error': 'Invalid Username or Password',
                    'title': 'Login',
                    'subtitle': 'Form',
                }
                # messages.success(request, f'Selamat Datang , {user.username}')
                return render(request, 'manajemen_cuti/login.html', context)
        else:
            # print("Form errors:", form.errors)
            # messages.error(request, 'Username atau Password anda salah.')
            # messages.error(request, 'Form tidak valid. Coba lagi.')
            context = {
                'forms': form,
                'error': 'Invalid Username or Password',
                'title': 'Login',
                'subtitle': 'Form',
            }
            return render(request, 'manajemen_cuti/login.html', context)
    
    # Get request
    form = AuthenticationForm()
    context = {
        'title' : 'Login Form',
        'forms' : form,
    }
    return render(request, 'login.html', context)

def user_logout(request):
    logout(request)
    return redirect('manajemen_cuti:login')

manajemen_cuti/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login form</title>
</head>
<body>
    <form action="" method="POST"">
        {% csrf_token %}
        {{ forms.as_table }}
        <input type="submit" value="login">
    </form>
</body>
</html>

manajemen_cuti/templates/manajemen_cuti/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <h3>{{ title }}</h3>
    <div class="row">
        <div class="col-md">
            <div class="card card-default">
                <div class="card-body">
                    {% if messages %}
                        {% for message in messages %}
                        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-error{% endif %}">
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md">
                                <div class="form-group">
                                    <label for="jenis_cuti">Jenis Cuti :</label>
                                    {{ forms.jenis_cuti }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md">
                                <div class="form-group">
                                    <label for="tgl_mulai">Tgl Mulai :</label>
                                    {{ forms.tgl_mulai }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md">
                                <div class="form-group">
                                    <label for="tgl_selesai">Tgl Selesai :</label>
                                    {{ forms.tgl_selesai }}
                                </div>
                            </div>
                        </div>
                        <!-- <div class="row">
                            <div class="col-md">
                                <div class="form-group">
                                    <label for="status">Status :</label>
                                    {{ forms.status }}
                                </div>
                            </div>
                        </div> -->
                        <div class="row">
                            <div class="col-md">
                                <div class="form-group">
                                    <label for="alasan">Alasan :</label>
                                    {{ forms.alasan }}
                                </div>
                            </div>
                        </div>
                        <input type="submit" value="Simpan">
                        <!-- <button type="submit" class="btn btn-success d-flex align-items-center justify-content-center mr-2" style="width: 100px;">
                            <ion-icon name="save-outline" style="width: 25px; height: 25px; margin-right: 5px;"> </ion-icon> Save
                        </button> -->
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

manajemen_cuti/templates/manajemen_cuti/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <h3>{{ title }}</h3>
    <h4>selamat datang {{ request.user }}</h4>

    <a href="{% url 'manajemen_cuti:add_cuti' %}">Ajukan Cuti</a>
    <table border="1">
        <thead>
            <th>No</th>
            <th>karyawan</th>
            <th>jenis cuti</th>
            <th>tgl permohonan</th>
            <th>tgl mulai</th>
            <th>tgl selesai</th>
            <th>status</th>
            <th>alasan</th>
            <th>Sisa Cuti</th>
        </thead>
        <tbody>
            
            {% for c in cutis  %}

            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ c.karyawan }}</td>
                <td>{{ c.jenis_cuti }}</td>
                <td>{{ c.tgl_permohonan }}</td>
                <td>{{ c.tgl_mulai }}</td>
                <td>{{ c.tgl_selesai }}</td>
                <td>
                    
                    {% if c.status == 'pending' and user.is_staff %}
                        <a href="{% url 'manajemen_cuti:approve_cuti' c.id %}">Setujui </a>|
                        <a href="{% url 'manajemen_cuti:reject_cuti' c.id %}">Tolak</a>
                    {% elif c.status == 'disetujui' and user.is_staff %}
                        <a href="{% url 'manajemen_cuti:cancel_cuti' c.id %}">Batalkan</a>
                    {% else %}
                        {{ c.status }}
                    {% endif %}
                    
                    <!-- {% if c.status == 'disetujui' and user.is_staff %}
                        <a href="{% url 'manajemen_cuti:cancel_cuti' c.id %}">Batalkan</a>
                    {% endif %} -->
                        
                <td>{{ c.alasan }}</td>
                <td> {{ c.sisa_cuti }}</td>
            </tr>
                
            {% endfor %}
                
        </tbody>
    </table>
    <a href="{% url 'manajemen_cuti:logout' %}">logout</a>
</body>
</html>